### ISSUE TITLE
CSS: Červená na červenej

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#101]
... je strašne zle viditeľná. Chceme s tým niečo robiť?
(Týka sa to len neaktívnych položiek, otázka je či treba.)

**Comment by ViRPo** [comment]
Jasne, dam ich trochu bledsou

**Comment by mrshu** [comment]
@ViRPo @tvinar neviem, ci sa toto uz nejako zmenlo, ale mne osobne az tak necitatelna ta cervena nepride. Ak je zaujem tu farbu menit, som urcite za, ale ak na to nezostane cas, myslim, ze je to velmi prijatelne aj v aktualnom stave.

**Comment by ViRPo** [comment]
@mrshu na bete je uz zmenena
