### ISSUE TITLE
Adresa bez obce

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#102]
Adresu je možné zadať aj bez obce.
Možno by bolo dobré pridať kontrolu: ak je vyplnená ulica musí byť zvolená aj obec.
(buď do validátorov alebo do záverečných kontrol).

**Comment by mrshu** [comment]
@tvinar Ok, co vsak v pripadoch, ked sa jedna o zahranicnu adresu? Vtedy neriesit?

**Comment by tvinar** [comment]
Vtedy by mala byt vyplnena zahranicna obec ;)

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207
