### ISSUE TITLE
Kontrola kombinácie kódov študijných programov a škôl

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#103]
V záverečných kontrolách by bolo dobré pridať nasledovné kontroly a v prípade problému upozorniť na nezhody (warning, nie chybu):
- Ak je vyplnený kód študijného odboru a dosiahnuté vzdelanie, tak by malo sedieť 5 písmeno kódu so vzoleným kódom vzdelania.
- Ak je zvolená stredná škola a kód študijného odboru, tak by mal byť študijný odbor vyučovaný na tej škole. (jedná sa o číselník, ktorý vyexportujem z AIS2 a uložím do Dropboxu ;)

**Comment by tvinar** [comment]
Prislusny ciselnik je 714-odbory-vyucovane-na-SS.xlsx

**Comment by mrshu** [comment]
@tvinar Pridal som dva warningy:

> Ak je vyplnený kód študijného odboru a dosiahnuté vzdelanie, tak by malo sedieť 5 písmeno kódu so vzoleným kódom vzdelania.

Warning hovori: *Vaše dosiahnuté / očakávané stredoškolské vzdelanie nekorešponduje s vami zadaným kódom študijného odboru. Zmeniť Vaše dosiahnuté / očakávané stredoškolské vzdelanie alebo študijný odbor možete v časti Predchádzajúce štúdium .*

> Ak je zvolená stredná škola a kód študijného odboru, tak by mal byť študijný odbor vyučovaný na tej škole. (jedná sa o číselník, ktorý vyexportujem z AIS2 a uložím do Dropboxu ;)

Warning hovori: *Vaša kombinácia navštevovanej strednej školy a študijného odboru nebola nájdená v našej databáze. Zmeniť navštevovanú strednú školu alebo študijný odbor možete v časti Predchádzajúce štúdium .*

Da sa to otestovat ako na bete ale aj na produkcii.
