### ISSUE TITLE
Lepšia správa pri chýbajúcom rodnom čísle, dátume narodenia

### ISSUE THREAD

**Issue by Sameth** [fmfi-svt/eprihlaska#108]
Pokiaľ nevyplním nič do rodného čísla ani dátumu narodenia, dostanem aj tak chybu "Zadali ste nesprávne r.č. ...", resp. "Správny formát je ...".

Namiesto toho by sa mohlo zobraziť niečo typu "Prosím, vyplňte <bla>".

**Comment by mrshu** [comment]
@Sameth Urcite suhlasim.

Fix by mal byt velmi jednoduchy, malo by stacit pridat nieco ako

```
if not field.data:
    raise validators.ValidationError(self.empty_message)
```

Kde `self.empty_message` bude prave sprava "prosim vyplnte" niekde okolo [tohto riadku](https://github.com/fmfi-svt/eprihlaska/blob/master/eprihlaska/validators.py#L45) (cc @JakubNvk ).

Pull request je velmi vitany! =)
