### ISSUE TITLE
Nie vsetky obce z ciselnika vie AIS najst

### ISSUE THREAD

**Issue by mrshu** [fmfi-svt/eprihlaska#109]
V kontexte adresy napriklad nedokaze najst "Adamovské Kochanovce".

**Comment by mrshu** [comment]
Ukazalo sa, ze v kontexte adresy mesto nemoze byt dva a viac slovne, avsak v kontexte miesta narodenia je to v poriadku...

**Comment by tvinar** [comment]
toto patri do AIS2 bugov, nie do nasich...

**Comment by mrshu** [comment]
> toto patri do AIS2 bugov, nie do nasich...

Pravda, zatvaram.
