### ISSUE TITLE
AIS2 IMPORT: vypĺňanie tabuľky predmetov

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#112]
V tabuľke predmetov sa môže už predvyplniť nejaký zoznam predmetov, podľa toho aké nastavenia má uložené príslušná referentka. Preto pred napĺňaním tabuľky treba **vymazať všetky riadky, ktoré tam potenciálne existujú**

**Comment by mrshu** [comment]
@tvinar Vdaka, pre istotu vsetky vymazavame.
