### ISSUE TITLE
Trackovanie vykonania poslednej zmeny

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#127]
ak zmenime stav prihlasky na napr. rozpracovanu, aby uchadzac mohol vykonat zmenu a po zmene on opat poda, tak napriek tomu, ze poslednu zmenu vykonal ten uchadzac, tak meno pri Autor poslednej zmeny nie je user.
Pozri napr. pri Marii Fuksovej.
a minuli som ja odblokovala prihlasku a ked uchadzac opat podal, tak autor poslednej zmeny som bola ja.

**Comment by mrshu** [comment]
Toto bol naozaj problem, ale uz by mal byt vybaveny (otestoval som to aj v prodkucii).

Vdaka za report!
