### ISSUE TITLE
Ukončovací protokol

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#129]
12.3.2018 je ukončenie podávania prihlášok.
Správanie by malo byť nasledovné:
- na úvodnej stránke je vypísaný oznam "Podávanie prihlášok momentálne nie je otvorené. Ak ste podali prihlášku, môžete si jej stav overiť po prihlásení."
- po prihlásení: ak má používateľ podanú prihlášku, tak ako doteraz; endpointy na vypĺňanie prihlášky sa presmerujú na oznam "Podávanie prihlášok momentálne nie je otvorené."

**Comment by mrshu** [comment]
Vidim to na config option.

**Comment by tvinar** [comment]
Ano, config option je dobre riesenie, akurat ju treba naimplementovat a
otestovat do buduceho tyzdna.
(Vypiname 13.3.)

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207
