### ISSUE TITLE
Chýbajú koncoročné známky z informatiky

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#133]
Chýba zadávanie koncoročných známok z informatiky.

**Comment by mrshu** [comment]
Toto sme nejako kompletne odignorovali -- osobne si to teda vobec nepamatam :)

Pre ake programy to treba zapnut?

**Comment by mrshu** [comment]
z komentaru od @tvinar:
> informatika, bioinformatika
> (aplikovaná informatika ani učiteľstvá nie, pretože tie nezohľadňujú známky na koncoročných vysvedčeniach)
