### ISSUE TITLE
Pole poznámka

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#134]
Doplniť pole Poznámka - najlepšie na stránku č. 7 - podanie prihlášky.
Limitovať povedzme na 1000 znakov.

**Comment by mrshu** [comment]
Toto bude predsa len trochu narocnejsie -- bude treba vyrobit novy `FlaskForm`, ktory bude robit odosielanie prihlasky. Mierne to preto zmeni architekturu tej poslednej (podavacej) stranky.
