### ISSUE TITLE
final.html chybny rok

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#146]
riadok v template: 
{% if session['basic_personal_data']['matura_year'] == 2018 %}
ma byt
== 2019

Neda sa tam dat nejaka konstanta (current_matura_year alebo nieco podobne), nech sa na to nezabudne kazdy rok?

**Comment by Adman** [comment]
Toto bude urcite treba pridat do nejakeho configu. Najlepsie takeho, v ktorom budu presne taketo veci, ktore sa kazdy rok menia.
Alebo ma by sme este mohli spravit taky admin interface, v ktorom to na par klikov budeme vediet prestavit. @mrshu co na to hovoris?

**Comment by tvinar** [comment]
Taketo veci sa davaju do costs.py
Uz to existuje v consts.py (premenna CURRENT_MATURA_YEAR), akurat to treba
nahradit spravne v tom template (tam je natvrdo z minuleho roku 2018).

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

**Comment by Adman** [comment]
Hej, o costs.py viem, ale do buducna by sme to mohli upratat tak, aby bolo jasne, co treba kazdy rok pomenit.

**Comment by mrshu** [comment]
Ta filozoficka otazka, ktoru sa (aspon myslim) @Adman pyta je, ze ci je naozaj spravne, aby boli taketo veci v `consts.py` a ci by nemali byt radsej v `config.py` alebo niekde podobne.

Za mna je to nateraz (pri jednej instancii) jedno, aj ked je pravda, ze by sa mi viacej pacilo menit pri deploymente aplikacie iba jeden subor (teda napriklad `config.py`). Kedze sa ale tento rok meni s tym, ako sa meni aplikacia (teda nie pri kazdom novom deploymente ale doslova "z roka na rok"), myslim, ze znesieme aj `consts.py`.
