### ISSUE TITLE
Po vytlačení prihlášky sa neiniciuje refresh stránky

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#159]
Prihláška tesne po vytlačení sa nepresunie do príslušnej záložky, treba ručne reloadnuť stránku.

**Comment by mrshu** [comment]
Toto je velmi srandovna situacia.

Tak ono sa to aj naozaj reloaduje, ale kedze sme po problemoch s `pdftk` preradili zmenu stavu v DB az skoro priamo pred posielanie odpovede, v case, ked sa uz stranka reloadne ma podla vsetkeho este stale rovnaky status ako predtym.

Dvoma slovami, timeout treba.

Skusim vybavit.

**Comment by mrshu** [comment]
Malo by byt vybavene.
