### ISSUE TITLE
Zahranicni mozu mat rodne cislo

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#16]
Clovek moze mat priradene rodne cislo aj ked sa narodil v zahranici
(momentalne ak vyplnim krajinu narodenia v zahranici, tak sa rodne cislo neda vyplnit, lebo tam nie je)

**Comment by tvinar** [comment]
komentár k rodnému číslu by mal zniet:
pokiaľ ste občanom SR alebo vám rodné číslo bolo pridelené úradmi v SR

**Comment by mrshu** [comment]
To som dufal, ze je pekna featura =)

Ako vsak potom validovat to rodne cislo? Ak je nejake zadane, tak to riesit a ak nieje, tak tiez taky vstup akceptovat?

**Comment by tvinar** [comment]
Ak nie je zadane ziadne rodne cislo, tak je to validne v pripade, ze
obcianstvo nie je "Slovenska republika"
Alebo moze byt aj jednoduchsie, ako navrhujes (t.j. ak nieco zadas, tak sa
validuje, ak nezadas, tak sa nevaliduje)

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

2017-12-18 21:09 GMT+01:00 Marek Šuppa <notifications@github.com>:
