### ISSUE TITLE
Impersonate feature

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#165]
Administrátor prihlásený cez cosign by sa mohol vedieť prihlásiť ako ktorýkoľvek e-mail.
Ľahšie by sa debugovali potom issues, ktoré sa týkajú len konkrétneho používateľa.

**Comment by mrshu** [comment]
@tvinar velmi dobry napad -- vdaka zan!

V principe mam len jedinu poznamku: ako presne by fungovalo ukladanie dat? Co sa hlavne pytam je, ze ci ma administrator v tomto impersonovacom mode mat moznost menit uzivatelske data -- dost od toho zavysi komplexita takehoto niecoho.

**Comment by tvinar** [comment]
No, podla mna impersonovaci mod jednoducho funguje tak, ze za urcitych
okolnosti povolis login_user aj inym, ako tym pouzivatelom.

Konkretne implementacne, podla mna endpoint /admin/login/user/<email>,
ktory urobi v zasade to iste /login, akurat nekontroluje heslo ani inu
autentifikaciu; predpokladam, ze /admin/login/user bude zacosignovane a ze
bude mat @require_remote_user. Dava to zmysel?

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

**Comment by mrshu** [comment]
@tvinar Urcite dava, jedina moja otazka je, co sa stane, ked takto impersonovany pouzivatel zacne menit uzivatelske data. To uz je mierne komplexne osetrit. 

Ale v principe nieje problem to presne takto spravit, aj som to prakticky uplne presne rovnako planoval vyskusat :)

**Comment by tvinar** [comment]
>
>
> @tvinar <https://github.com/tvinar> Urcite dava, jedina moja otazka je,
> co sa stane, ked takto impersonovany pouzivatel zacne menit uzivatelske
> data. To uz je mierne komplexne osetrit.
>
To by som povazoval za feature, nie bug ;)


>

**Comment by mrshu** [comment]
@tvinar Ok, roger that :)

**Comment by Adman** [comment]
https://github.com/fmfi-svt/eprihlaska/pull/167
