### ISSUE TITLE
Meno a priezvisko presunut na uvodnu stranku

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#17]
Meno, priezvisko a rodne priezvisko by som presunul na uvodnu stranku.
(je hlupe ked sa hned ako prve pytame na list dekana a na rok maturity, aj ked je to z nasho pohladu logicke, tak sa spytajme ako prve aspon "kto vlastne si")

Meno a priezvisko by som potom zobrazoval v tom dolnom kontrolno bare (vyplnate prihlasku...)

Otazka je, ci by potom nebolo jednoduchsie / prehladnejsie mat jednu stranku s osobnymi udajmi
pripadne presunut rodne cisla a pod. na tu predchadzajucu a na druhej nechat len "Informacie o rodicoch" (a aj tak ju nazvat)

**Comment by mrshu** [comment]
> Otazka je, ci by potom nebolo jednoduchsie / prehladnejsie mat jednu stranku s osobnymi udajmi
pripadne presunut rodne cisla a pod. na tu predchadzajucu a na druhej nechat len "Informacie o rodicoch" (a aj tak ju nazvat)

Malo by to byt vybavene tak, ako je popisane v tomto odstavci. Ak niekto skusal nejaku predchadzajucu verziu, odporucam premazat cookies -- prestanu zrejme fungovat.

Vdaka!
