### ISSUE TITLE
Texty pre prihlasku

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#18]
Docasny text na stranke uvod (keby sa niekto NAHODOU na tuto adresu dostal v tomto stadiu):

Toto je testovacia verzia elektronickej prihlášky, ktorá nie je v prevádzke.
Ak hľadáte aktuálnu elektronickú prihlášku, použite stránku https://e-prihlaska.uniba.sk/

Na stranke Uvod:

Vitajte v systéme elektronickej prihlášky Fakulty matematiky, fyziky a informatiky Univerzity Komenského v Bratislave. Pomocou tohto systému sa môžete prihlásať na bakalárske štúdium. Informácie o študijných programoch nájdete na stránke https://fmph.uniba.sk/studium/programy/

Osobné údaje na tejto stránke sú spracúvané za účelom prijímacieho konania na fakultu na základe
zákona č. 131/2002 o vysokých školách v znení neskorších predpisov.

Na stránke "Predchádzajúce štúdium":

Ku "navštevovaná stredná škola" doplniť text:
V prípade, že vaša stredná škola nie je v zozname, zvoľte možnosť "moja stredná škola nie je v zozname"

Ku "kód študijného programu" doplniť text:
Kód študijného programu je uvedený na vašom vysvedčení. V prípade, že na vysvedčení nemáte uvedený jeden z týchto študijných kódov, zvoľte "študijný program mimo číselníka"

Na stránke "Prijatie bez prijímacích pohovorov" doplniť text:
Na tejto stránke uvádzate vybrané výsledky dosiahnuté počas strednej školy, ktoré majú vplyv na možné prijatie bez prijímacích pohovorov. Úplné podmienky prijatia bez prijímacích pohovorov nájdete na stránke https://fmph.uniba.sk/prihlasky/

Na stránku "Záverečné pokyny" potrebné pridať:

Ďakujeme za vyplnenie údajov. Pomocou nasledujúcej linky si skontrolujte , že všetky údaje boli vyplnené správne: Formulár elektronickej prihlášky (PDF) - linka

Podaním prihlášky potvrdzujete správnosť vyplnených údajov. Po podaní prihlášky už nie je možné údaje modifikovať. 

tlačidlo PODAŤ PRIHLÁŠKU

Ak bola prihláška podaná, tak sa objavia nasledovné pokyny:

Vaša elektronická prihláška bola podaná. V prípade, že ste prihlášku podali omylom alebo je nevyhnutné zmeniť údaje v prihláške, kontaktujte prosím študijné oddelenie FMFI UK (e-mail: so@fmph.uniba.sk, telefón 02/602 95 152)

Formulár elektronickej prihlášky (PDF) - linka
Vaša prihláška je v stave: [ prijatá / spracovaná ]
(prijatá = v našom systéme ale nie v AIS2,  spracovaná = preklopená do AIS2)

ČO JE POTREBNÉ UROBIŤ ĎALEJ?
[ak nemá list dekana]
- Poplatok za prijímacie konanie vo výške 33 EUR je potrebné uhradiť na účet číslo SK88 8180 0000 0070 0013 8327 variabilný symbol: 800 špecifický symbol: [rodné číslo bez lomky alebo ak nemá rodné číslo tak treba dať niečo typu 9999+vygenerované číslo prihlášky]
Potvrdenie o zaplatení si odložte pre prípad, že by sa vyskytol problém pri spárovaní vašej platby
s prihláškou.
[ak maturoval v roku 2017 alebo skôr:]
- Najneskôr do 14 dní nám pošlite poštou overenú kópiu Vášho maturitného vysvedčenia na adresu:
  Fakulta matematiky, fyziky a informatiky UK, Mlynská dolina, 842 48 Bratislava
[ak vypĺňal koncoročné známky:]
- Najneskôr do 14 dní nám pošlite poštou potvrdený formulár s výpisom známok alebo overené kópie príslušných koncoročných vysvedčení na adresu:
  Fakulta matematiky, fyziky a informatiky UK, Mlynská dolina, 842 48 Bratislava
  Formulár výpis známok (PDF) - linka
[ak maturuje v roku 2018]
- Po skončení maturity nám bezodkladne pošlite overenú kópiu maturitného vysvedčenia, aby sme mohli vyhodnotiť splnenie podmienok pre prípadné prijatie bez prijímacieho konania. Kópiu maturitného vysvedčenia pošlite na adresu:
  Fakulta matematiky, fyziky a informatiky UK, Mlynská dolina, 842 48 Bratislava
[pre všetkých]
- O ďalšom postupe prijímacieho konania (predbežné alebo podmienečné rozhodnutie o prijatí, pozvánka na prijímacie pohovory, rozhodnutie o neprijatí a pod.) vás budeme včas informovať písomne listom na adresu, ktorú ste uviedli v tejto prihláške. V prípade akýchkoľvek otázok nás prosím kontaktujte (e-mail: so@fmph.uniba.sk, telefón 02/602 95 152)

**Comment by mrshu** [comment]
Viacero z tychto textov by sa uz v prihlaske malo objavit, pevne verim, ze dnes pribudnu este dalsie.

**Comment by mrshu** [comment]
Prihlaske chybaju uz iba zaciatocne texty, v ktorych by sa mala samotna prihlaska nakoniec finalne podat. Tie pribudbu s databazou.

**Comment by tvinar** [comment]
Zatiaľ stále chýba explicitné "PODANIE PRIHLÁŠKY" po overení správnosti všetkých podaných údajov.
Po podaní prihlášky ju už nemožno meniť a dovtedy je evidujeme len ako niečo rozpracované (čo sa zatiaľ nebude preklápať do AIS2).

Špecifikácia viď vyššie.

Toto je dôležité a asi to ovplyvňuje trochu štruktúru.
Chceme z toho urobiť separátnu issue? (A v každom prípade ju treba čím skôr doriešiť)

**Comment by mrshu** [comment]
@tvinar explicitne podanie prihlasky by uz malo byt vybavene, prilis to strukturu nastastie nezmenilo.
