### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#22]
Submit button by sa mohol volať po slovensky, napriklad "Uložiť"
Okrem toho, ak niekoho nenapadne, že sa tam dá hore preklikávať, možno by mohol existovať aj button "Späť"

**Comment by mrshu** [comment]
> Submit button by sa mohol volať po slovensky, napriklad "Uložiť"
Mozeme vybavit.

> Okrem toho, ak niekoho nenapadne, že sa tam dá hore preklikávať, možno by mohol existovať aj button "Späť"
Toto je nateraz trochu narocnejsie, ale ked budeme robit design refinement mozeme kludne aj toto spravit
