### ISSUE TITLE
Kontrola rodneho cisla

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#28]
Pri ľuďoch s neslovenským občianstvom sa vyžaduje rodné číslo a nemá sa.
Pravdepodobne sa kontroluje podľa občianstva uloženého v session a nie v requeste ?
Možný hotfix 1: povoliť hocikomu nezadať rodné číslo
Možný hotfix 2: presunúť položku občianstvo do časti "Úvod"

**Comment by mrshu** [comment]
> Pri ľuďoch s neslovenským občianstvom sa vyžaduje rodné číslo a nemá sa.

Hmm, toto neviem nakolko je konzistentne v #9, kde sa pise:

> Clovek moze mat priradene rodne cislo aj ked sa narodil v zahranici (momentalne ak vyplnim krajinu narodenia v zahranici, tak sa rodne cislo neda vyplnit, lebo tam nie je)

Chcel som to riesit tak, ako pisal posledny komentar v #9, teda:
> Alebo moze byt aj jednoduchsie, ako navrhujes (t.j. ak nieco zadas, tak sa validuje, ak nezadas, tak sa nevaliduje)

Mohlo by to byt tak?

~~~~~~~~~~~~~~~~~~~~~`

PS: pred prehadzovanim fieldov sme mali na to aj nejaku logiku, ale ta uz je teraz dost irelevantna (a teda na vymazanie): https://github.com/fmfi-svt/eprihlaska/blob/master/eprihlaska/views.py#L61

**Comment by tvinar** [comment]
>
> Pri ľuďoch s neslovenským občianstvom sa vyžaduje rodné číslo a nemá sa.
>
> Hmm, toto neviem nakolko je konzistentne v #9
> <https://github.com/fmfi-svt/eprihlaska/issues/9>, kde sa pise:
>
> Clovek moze mat priradene rodne cislo aj ked sa narodil v zahranici
> (momentalne ak vyplnim krajinu narodenia v zahranici, tak sa rodne cislo
> neda vyplnit, lebo tam nie je)
>
> Chcel som to riesit tak, ako pisal posledny komentar v #9
> <https://github.com/fmfi-svt/eprihlaska/issues/9>, teda:
>
> Alebo moze byt aj jednoduchsie, ako navrhujes (t.j. ak nieco zadas, tak sa
> validuje, ak nezadas, tak sa nevaliduje)
>
> Mohlo by to byt tak?
>

Suhlas.


> PS: pred prehadzovanim fieldov sme mali na to aj nejaku logiku, ale ta uz je teraz dost irelevantna (a teda na vymazanie): https://github.com/fmfi-svt/eprihlaska/blob/master/eprihlaska/views.py#L61
>
> Suhlas.

**Comment by mrshu** [comment]
Ok, vdaka, tuto issue teda zatvorim ako duplikat #9 (cc @JakubNvk)
