### ISSUE TITLE
Rodne cislo + datum narodenia

### ISSUE THREAD

**Issue by ViRPo** [fmfi-svt/eprihlaska#30]
Je bezne pytat si aj rodne cislo aj datum narodenia?
My ich mame hned pod sebou, no ide v podstate o ten isty udaj

**Comment by mrshu** [comment]
Myslim, ze sa to tak asi bezne robi pri takychto formularoch.

Zda sa mi, ze nas problem je tu aj ten, ze rodne cislo sa pytame pre tych, ktori ho maju priradene, ale datum narodenia by sme chceli od vsetkych. Mozeme mozno spravit to, ze ked niekto ma rodne cislo (a je validne), nejako ho doratame namiesto toho, aby sa to muselo zadavat.

**Comment by ViRPo** [comment]
Aj take doratanie mi napadlo, ale myslim si, ze by to bol zatial overkill, netreba sa na take detaily sustredit
Zabudol som uplne napriklad na zahranicnych studentov, ponechat obe polia mi pride v danu chvilu najrozumnejsie

**Comment by mrshu** [comment]
Vdaka za odpoved, tuto issue teda zatvorim. Kludne otvor novu, ak by to zacalo byt znova relevantne.
