### ISSUE TITLE
Rodné priezvisko u mužov

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#35]
Treba rodné priezvisko požadovať aj od mužov? Ak nie, tak ak by sa dal výber pohlavia pred túto položku, tak by sa nemusela vôbec pri mužoch ukazovať.

**Comment by tvinar** [comment]
Aj muži môžu zmeniť priezvisko z rôznych dôvodov.
(napríklad si zoberú priezvisko manželky)/.
