### ISSUE TITLE
Prvý študijný program - žiaden

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#36]
Ak zadám tri študijné programy a potom prvý zmením na žiaden, tak by sa to asi nemalo považovať za korektne vyplnenú prihlášku. Navrhujem nepustiť ďalej alebo druhý tretí posunúť na prvý druhý.

**Comment by tvinar** [comment]
Dôležité je, čo presne posunieme ďalej (t.j. keď sa to bude hádzať do formulárov a do AIS2, nevyplnené položky treba ignorovať).

Nevidel by som to ako dôležitý prvok user interface.

**Comment by mrshu** [comment]
Toto by sme mohli asi aj oznacit za fixnute, kedze aktualne uz prihlaska nepusti dalej, ak prvy studijny program nieje vybrany (vid https://github.com/fmfi-svt/eprihlaska/blob/master/eprihlaska/views.py#L117).

**Comment by mrshu** [comment]
Dohodol som sa sam so sebou, ze toto zavrieme.

Kludne tuto issue, prosim, otvorte, ak sa vam to nezda byt spravne.

Vdaka!
