### ISSUE TITLE
Študijné programy obsahujú osobné údaje

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#37]
Študijné programy obsahujú časti:
* OSOBNÉ ÚDAJE
* ŠTUDIJNÉ PROGRAMY
ale pritom až ďalšia sekcia sa volá Osobné údaje. Nie je to mätúce?

**Comment by tvinar** [comment]
* V časti "ŠTUDIJNÝ PROGRAM" by som premenoval sekciu "OSOBNÉ ÚDAJE" na "ZÁKLADNÉ ÚDAJE".
* Rodinný stav a Pohlavie by som presunul do sekcie 2 "Osobné údaje"
* Položky "Rok maturity" a "Dostal som list od dekana" by som presunul vyššie do sekcie "Základné údaje"

**Comment by mrshu** [comment]
Vdaka, malo by to byt vybavene.
