### ISSUE TITLE
Rodné číslo a dátum narodenia

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#39]
Rodné číslo akceptuje aj 310231/1234. Je to síce deliteľné 11, ale február zjavne nemá 31 dní.
Takáto "hlbšia" validácia RČ hneď evokuje, či by sa po zadaní RČ nemohol automaticky vyplniť aj dátum narodenia.

**Comment by mrshu** [comment]
Validovat datum sme sa zatial nesnazili, hlavne koli tomu, aby sme mali kostru aplikacie co najskor. Ak vsak bude cas, isto by sa hlbsie zvalidovat datum mohol (cc @JakubNvk).

Automaticky vyplnat datum narodenia je trochu problem -- rodne cislo validujeme na backende, kdezto predvyplnanie datumu narodenia by sme zrejme robili na frontende.
