### ISSUE TITLE
Občianstvo -> Krajina narodenia

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#40]
Pokiaľ krajina narodenia nie je vyplnená, tak zadanie občianstva by mohlo rovnakou hodnotou vyplniť krajinu narodenia. Následne (asi v málo prípadoch) by si ju používateľ mohol zmeniť, ak je iná ako občianstvo.

**Comment by tvinar** [comment]
Nie som si istý, že toto je užitočné. Keďže 95% používateľov má SR / SR, nechal by som jednoducho predvyplnené SR a neriešil by som.
