### ISSUE TITLE
Povinné položky

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#42]
Nechceme nejak označovať povinné položky. Napríklad:
OSOBNÉ ÚDAJE - Email je povinná položka, ale
OSOBNÉ ÚDAJE - Telefónny kontakt nie a pritom to nie je vidieť.
Rozdiel sa spozná až po kliknutí na ĎALEJ.

**Comment by tvinar** [comment]
Problém je v tom, že neexistuje presná definícia toho, čo je to minimálna prihláška a každý údaj je užitočný a v niektorých prípadoch aj potrebný (ale nie je jasné, čo to znamená "niektoré prípady").

Ak by sme ohviezdičkovali len skutočne najpovinnejšie položky, potom by sa našli používatelia, ktorí by vypĺňali len tie, a to by nám pravdepodobne neprinieslo dostatok informácie... (t.j. bolo by ich treba dodatočne kontaktovať).

Ja by som teda navrhoval nechať bez označenia a robiť minimálne kontroly tak ako doteraz.
