### ISSUE TITLE
ADRESA TRVALÉHO BYDLISKA: Mesto -> PSČ

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#43]
Pre SR by mohol výber Mesta predvyplniť PSČ. Používateľ by si ho následne mohol doeditovať, ak bude treba (asi iba pre veľké mestá).

**Comment by tvinar** [comment]
S tým číselníkom PSČ sa dosť zle robí. Vo všeobecnosti s tým asi používateľ nemá problém vyplniť to a skôr preskakujúce predvyplnené hodnoty ho môžu spomaliť, takže výsledná user experience môže byť horšia.

Takže ja by som takéto veci odložil na čas, keď už fakt nebudeme mať nič iné na práci ;)

**Comment by mrshu** [comment]
Taku jednoduchu vec som teda pridal: to PSC sa iba predvyplni podla obce/mesta.

Neviem, ci je to takto dobre, ale ak je, zavrite prosim tuto issue.

Vdaka!

**Comment by mrshu** [comment]
Pre lepsiu prehladnost toto zatvaram -- ak by to dobre nefungovalo, otvorte prosim dalsiu issue.

Vdaka!
