### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#45]
Keď chcem prejsť z "Predchádzajúce štúdium" na ďalšiu časť "Prijatie bez prijímacích pohovorov" tak dostanem: Internal Server Error.

Má to súvis s "Dostal som list od dekana". Ak som nedostal, tak to ide.

**Comment by mrshu** [comment]
Mozete prosim presnejsie popisat v akej situacii dostanete Internal Server Error? Zatial sa mi zial nepodarilo tento problem zreprodukovat.

Vdaka!

**Comment by JakubNvk** [comment]
Myslim, ze toto mi sposobovalo nepremazanie cookies ked som sa hral s prihlaskou.

**Comment by mrshu** [comment]
> Myslim, ze toto mi sposobovalo nepremazanie cookies ked som sa hral s prihlaskou.

Moze byt, ospravedlnujem sa, je to hlavne tym, ze sa tam veci velmi rychlo menia (a teda hlavne za behu).

**Comment by ostertag** [comment]
Už to neviem ani ja reprodukovať. Možno sa niečo zmenilo alebo to bolo v niečom úplne inom.
