### ISSUE TITLE
ZÁVEREČNÉ POKYNY

### ISSUE THREAD

**Issue by ostertag** [fmfi-svt/eprihlaska#47]
V popise na tejto strane by mala byť uvedená aj informácia, či sa môžem opätovne prihlásiť do systému ePrihlaska. Ak áno, a môžem aj meniť už zadané údaje, tak by bolo fajn uviesť aj dokedy.

**Comment by mrshu** [comment]
Toto by uz malo byt vybavene vdaka commitu https://github.com/fmfi-svt/eprihlaska/commit/60500342d110a793bb3474f086b435ae4e3e271e

Vdaka za poznamku!
