### ISSUE TITLE
SCIO výsledky

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#50]
Momentálne tam je jedna položka: percentil / dátum vykonania autorizovanej skúšky z matematiky (SCIO)
Bolo by dobré ju rozdeliť na dve?
(percentil a dátum)

**Comment by mrshu** [comment]
@Adman @JakubNvk Mozete sa na toto prosim pozriet? Realne to asi znamena vymenit checkbox za dva `StringField`y a trochu pomenit konstanty v `costs.py`.
