### ISSUE TITLE
Ak je uzivatel prihlaseny, vypnut zobrazovanie "Zaregistrujte sa"

### ISSUE THREAD

**Issue by Adman** [fmfi-svt/eprihlaska#58]

**Comment by mrshu** [comment]
@Adman toto sa mysli na uvodnej stranke alebo aj niekde inde? Myslim, ze iba na indexe (`intro.html`) by sa toto mohlo zobrazovat. Ten index sa vsak bude (pevne verim) este menit

**Comment by Adman** [comment]
@mrshu na uvodnej som to nasiel

**Comment by mrshu** [comment]
@Adman vdaka, potom chapem. Pevne verim, ze sa ta prva stranka bude este menit, ale zatial teda nechame tuto issue otvorenu.

**Comment by mrshu** [comment]
@Adman Nejako som to fixol, ale aj tak sa zrejme ta prva stranka zmeni.

Vdaka!
