### ISSUE TITLE
Po odoslaní prihlášky by mali zmiznúť vypĺňacie časti

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#62]
Po odoslaní prihlášky by sa už nemali zobrazovať vypĺňacie časti formulára (1-7) iba záver (8), pričom v závere by mala byť ešte linka na HTML/PDF formulár prihlášky.

**Comment by mrshu** [comment]
Hmm, tu vidim dve moznosti:

1. nezobrazovat vyplnacie casti formulara a mat HTML/PDF view celej prihlasky
2. zobrazovat vyplacie casti formulara, ale nechat ich vsetky ako disabled (#54) 

Vyhodou moznosti 2. je, ze by sme sa mozno zaobisli bez toho HTML/PDF view, ktory nieje uplne trivialne spravit.

Ktore z tohto sa teda javi ako lepsia moznost?

**Comment by tvinar** [comment]
HTML / PDF view celej prihlasky potrebujeme tak ci tak.
To je ten material, ktory sa bude tlacit a archivovat a ktory si oni maju
skontrolovat pred finalnym odovzdanim.

Takze moznost 1.

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

2018-01-02 12:21 GMT+01:00 Marek Šuppa <notifications@github.com>:

**Comment by mrshu** [comment]
@tvinar Ok, teda moznost 1.

Otazkou zostava, ci ten formular existuje (i.e. je nejaky taky, ktory ma vsetky nalezitosti) alebo si ho mozeme nejakym sposobom vyrobit.

**Comment by tvinar** [comment]
Vyrobime si ho.
Moze ale nemusi sa inspirovat "standardnou" prihlaskou z ministerstva
skolstva.
(Minimalne by mohlo mat rovnake poradie udajov)

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

2018-01-02 14:09 GMT+01:00 Marek Šuppa <notifications@github.com>:

**Comment by mrshu** [comment]
Ok, bolo by mozne potvrdit, ze je to tento formular prihlasky?

https://www.minedu.sk/prihlaska-na-vysokoskolske-studium-bakalarske-%E2%80%93-prvy-stupen-alebo-spojene-%E2%80%93-prvy-a-druhy-stupen-v-jednom-celku/

**Comment by tvinar** [comment]
Ano, je to ono.
Ale format netreba brat moc vazne, ale podobne poradie poloziek by asi
pomohlo.

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

2018-01-02 16:23 GMT+01:00 Marek Šuppa <notifications@github.com>:

**Comment by mrshu** [comment]
Akysi listing som teda spravil. Neviem, ci je to tak dobre -- ak by s tym bol problem, bolo by asi dobre otvorit novy issue.

Vdaka!
