### ISSUE TITLE
grades_control revizia textov

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#67]
Možno logo fakulty vpravo?

Nadpis:
Potvrdenie ku prihláške na vysokoškolské štúdium

Univerzita: Univerzita Komenského v Bratislave
Fakulta: Fakulta matematiky, fyziky a informatiky
Akademický rok: 2018/2019

Ďalej môže pokračovať ako je. 
Do časti "Údaje o študentovi" doplniť Dátum narodenia
(aby to bolo identifikovateľné aj u Petrov Kováčov, ktorí náhodou neviedli rodné číslo)

**Comment by mrshu** [comment]
@tvinar Ako tak som to upravil, prosim pozriet, ci to takto moze byt (napr. ci zmena z title `ePrihlaska - Výpis vybraných známok` je ziaduca). Ak nie, prosim otvorit znova tento issue.

@ViRPo aj ked to v HTML vyzera ako tak, pri printe to uz je rapidne horsie. Mohol by si mi tu s CSSkami trochu pomoct? Vdaka!

**Comment by tvinar** [comment]
Hlavny nadpis je ok
Namiesto nadpisu prveho bloku "Potvrdenie ..." by som dal "Údaje o prihláške" a dovnútra za akademický rok by som dal "Evidenčné číslo prihlášky: eprih-2018-xxx" (to eprih-2018-. by som tam dal kvoli tomu, aby sa to neplietlo s inými evidenčnými číslami, ktoré potenciálne prihláške priradíme v rámci procesu)
