### ISSUE TITLE
V časti kontrola udajov uviesť upozornenia

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#68]
Konkrétne by som uviedol upozornenia:
- ak neuviedol rodné číslo "Neuviedli ste rodné číslo. Rodné číslo je potrebné uviesť, ak vám bolo pridelené."
- ak majú prázdnu ulicu v adrese "Neuviedli ste adresu trvalého bydliska. Nekompletné prihlášky nebudú môcť byť akceptované."

**Comment by mrshu** [comment]
@tvinar Chcel by som sa len spytat, v ktorej casti by sa toto malo riesit? Priamo pri zadavani adresy/rodneho cisla alebo az pri podavani prihlasky?

**Comment by tvinar** [comment]
Ja by som povedal, že až pri podávaní prihlášky.
Nech to neotravuje počas vypĺňania...

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

**Comment by mrshu** [comment]
Ok, predpokladam vsak, ze prihlasku by sa malo dat podat aj bez vyplneneho rodneho cisla, vsak?

**Comment by tvinar** [comment]
Ano.

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

**Comment by mrshu** [comment]
@tvinar Vdaka. Pridal som upozornenia. 

Kazdopadne som si uz nie celkom isty, ci je to take dobre riesenie v pripade prazdnej ulice: z toho upozornenia to vyzera tak, ze nevyplnena ulica znamena nevyplnenu prihlasku a teda by aspon ulica mala byt povinna. Ci som to zle pochopil?

**Comment by tvinar** [comment]
Mozeme dat aj alternativu ze ulica je jednoducho povinny udaj a basta.

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

2018-01-04 23:03 GMT+01:00 Marek Šuppa <notifications@github.com>:
