### ISSUE TITLE
Nespravne poradie zvolenych studijnych programov

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#7]
Studijne programy sa v ramci zvolenych programov preusporiadaju.
Napriklad ked si zvolim poradie "OZE INF FYZ" tak po Submite man "FYZ OZE INF"

Kriticky problem, kedze ziadatel si voli programy v poradi podla priority.

**Comment by mrshu** [comment]
Zial, toto neviem zreplikovat. Mne po submite zostanu v rovnakom poradi (vidno ho aj vo footeri).

**Comment by tvinar** [comment]
--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

**Comment by mrshu** [comment]
Malo by byt vybavene -- ak to este nieje dobre, prosim otvorit novy issue.
