### ISSUE TITLE
Vyhladavania by mohli ignorovat diakritiku

### ISSUE THREAD

**Issue by ViRPo** [fmfi-svt/eprihlaska#76]
Napr pri vyhladavani "Grosslingova" v zozname gymnazii nenajde "Grösslingová"

**Comment by mrshu** [comment]
Toto by bola naozaj paradna ficura.

Je trochu problem s tym, ze by to asi vyzadovalo upravit Chosen, ktory pouzivame, vid https://stackoverflow.com/questions/31960166/chosen-search-accented-words a https://github.com/harvesthq/chosen/pull/2618

Kazdopadne priechodne by to asi byt malo, vid demo na http://fiddle.jshell.net/whqb5/1/

**Comment by mrshu** [comment]
Dnes sme tiez zistili, ze kedze sa prida nazov okresu, mohlo by sa tiez zacat vyhladavat zo zaciatku stringu.

**Comment by mrshu** [comment]
@ViRPo toto by malo byt fixnute za cenu neminifikovanej a custom upravenej verzie kniznice `chosen.js`. Ak budes mat cas, bolo by to asi super zminifikovat, ale to zasa nieje asi vobec dolezite.
