### ISSUE TITLE
Uspech z IOI pri hlaseni sa na INF

### ISSUE THREAD

**Issue by ViRPo** [fmfi-svt/eprihlaska#77]
Pri prihlasovani sa na obor INF v uspechoch zo sutazi nefigurovala olympiada z informatiky
Je to tak zamerne @tvinar ?

**Comment by tvinar** [comment]
Je to chyba, ma tam byt aj informatika.

Presne podmienky su tu:
https://fmph.uniba.sk/fileadmin/fmfi/studium/prijimacky/KriteriaPrijmacky_1819_uplne_znenie.pdf
konkretne treba pozriet Tabulku 2 (profilove predmety) a znenie cl. 3 odst.
1.



--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

**Comment by mrshu** [comment]
Vdaka za pridanie issue, malo by byt fixnute v https://github.com/fmfi-svt/eprihlaska/commit/22b6b297a54efb588ddf32c959b91fe5982f60f3
