### ISSUE TITLE
Dátum narodenia - nepohodlný interface

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#8]
Dátum narodenia sa značne zle vyklikáva v kalendári. (+ Peťo sa sťažoval na nepohodlné vyklikávanie v mobile). Myslím, že oveľa pohodlnejšie by bolo nahradiť tento kalendárový widget napísaním normálneho dátumu s kontrolou tvaru dd.mm.yyyy.

**Comment by mrshu** [comment]
Ok, mozeme spravit tak.
