### ISSUE TITLE
ADMIN: zaheslovat

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#84]
Najlepsie pridat nejaku dalsiu uroven kontroly aj v kode
(t.j. ak nemam nasetovane user name v ziadnom systeme, nic nezobrazim).

**Comment by mrshu** [comment]
Zrejme sa tu pouzije [`REMOTE_USER`](https://stackoverflow.com/questions/20940651/how-to-access-apache-basic-authentication-user-in-flask) a nejaky [custom wrapper](http://flask.pocoo.org/snippets/8/).
