### ISSUE TITLE
CSS: Internet Explorer 11

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#89]
V IE11 sa to dosť rozsype, myslím že to je tým, že si o ňom myslí, že je to mobilný browser a podľa toho to aj vyzerá. (jeden stĺpec, hamburgrové menu, ...)

Takže treba komplexne skontrolovať funčnosť na Microsoftových browseroch a opraviť, čo opraviť treba.

**Comment by ViRPo** [comment]
Toto sme vyriesili v emailovom vlakne? @tvinar

**Comment by tvinar** [comment]
jj
