### ISSUE TITLE
Miesto narodenia - upratanie číselníka

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#9]
Miesto narodenia Košice-* a Bratislava-* nie je prípustné (v takom prípade sa používa len Košice resp. Bratislava) - to je špeciálny prípad. Takisto by bolo dobré to podľa niečoho zotriediť (napr. názov obce).

PSČ v Košiciach a Bratislave sú bordel, otázka je či je to problém len v Košiciach a Bratislave, alebo či to treba upratať aj v iných mestách. Pre miesto narodenia by stačilo uvádzať okres namiesto PSČ, u adries to môže byť iné.

**Comment by mrshu** [comment]
Malo by byt vybavene.

- Bratislava ma PSC 81101 (Bratislava 1)
- Kosice maju PSC 04001 (Kosice 1)

Obe sa zdaju byt relativne v poriadku. Ak to este bude problem, treba isto otvorit novy issue.

Vdaka!
