### ISSUE TITLE
Default mesto v adresach a v mieste narodenia

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#91]
V adresách je ako default nastavená Ábelová.
Default by mal byť nejaký NULL alebo niečo podobné s popisom "Zvoľte mesto alebo obec v SR"

**Comment by mrshu** [comment]
Ok, to je mozne spravit -- otazka je, ze ci sa ma vyzadovat nejaka odpoved ina ako tento NULL.

**Comment by tvinar** [comment]
U miesta narodenia ano
U adresy by som povedal ze kaslat na to.

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

**Comment by mrshu** [comment]
@tvinar vdaka, spravil som to tak -- u adresy sa kasle na to.
