### ISSUE TITLE
ADMIN: refresh pri tlačení

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/eprihlaska#94]
Pri tlačení sa neurobí refresh (tým pádom sa nepremietne nový stav "vytlačený")

**Comment by mrshu** [comment]
Stacilo by otvorit tu stranku s tlacenim a refreshnut tu, z ktorej sa na nu islo?

**Comment by tvinar** [comment]
jj

--
--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207
